baseURL: https://21sumdcs550.netlify.app
title: DCS 550 Summer 2021
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: J. Sihm
  description: It seems like everything is going well. 
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/yihui
    - icon: twitter
      name: Twitter
      url: https://twitter.com/xieyihui
